name: CI Pipeline

on:
  pull_request:
    branches:
      - main

jobs:

  validate:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - run: pip install dbt-snowflake
      - run: pip install sqlfluff
      - run: pip install sqlfluff-templater-dbt

      - name: SQL Lint
        run: sqlfluff lint dbt_project/customer_analytics/models

      - name: dbt Parse
        run: |
          cd dbt_project
          cd customer_analytics
          dbt parse